// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/datatunnel/v2/proto/proxy_control.proto

package proto // import "./proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProxyControlStreamMsgType int32

const (
	// 请求
	ProxyControlStreamMsgType_REQUEST ProxyControlStreamMsgType = 0
	// 响应
	ProxyControlStreamMsgType_RESPONSE ProxyControlStreamMsgType = 1
	// 通知,不需要响应
	ProxyControlStreamMsgType_NOTIFY ProxyControlStreamMsgType = 2
)

var ProxyControlStreamMsgType_name = map[int32]string{
	0: "REQUEST",
	1: "RESPONSE",
	2: "NOTIFY",
}
var ProxyControlStreamMsgType_value = map[string]int32{
	"REQUEST":  0,
	"RESPONSE": 1,
	"NOTIFY":   2,
}

func (x ProxyControlStreamMsgType) String() string {
	return proto.EnumName(ProxyControlStreamMsgType_name, int32(x))
}
func (ProxyControlStreamMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{0}
}

type ProxyControlStreamMsg struct {
	Hdr                  *ProxyControlStreamMsgHdr  `protobuf:"bytes,1,opt,name=Hdr,proto3" json:"Hdr,omitempty"`
	Body                 *ProxyControlStreamMsgBody `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ProxyControlStreamMsg) Reset()         { *m = ProxyControlStreamMsg{} }
func (m *ProxyControlStreamMsg) String() string { return proto.CompactTextString(m) }
func (*ProxyControlStreamMsg) ProtoMessage()    {}
func (*ProxyControlStreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{0}
}
func (m *ProxyControlStreamMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyControlStreamMsg.Unmarshal(m, b)
}
func (m *ProxyControlStreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyControlStreamMsg.Marshal(b, m, deterministic)
}
func (dst *ProxyControlStreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyControlStreamMsg.Merge(dst, src)
}
func (m *ProxyControlStreamMsg) XXX_Size() int {
	return xxx_messageInfo_ProxyControlStreamMsg.Size(m)
}
func (m *ProxyControlStreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyControlStreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyControlStreamMsg proto.InternalMessageInfo

func (m *ProxyControlStreamMsg) GetHdr() *ProxyControlStreamMsgHdr {
	if m != nil {
		return m.Hdr
	}
	return nil
}

func (m *ProxyControlStreamMsg) GetBody() *ProxyControlStreamMsgBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type ProxyControlStreamMsgHdr struct {
	MessageId            int64                     `protobuf:"varint,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	MessageType          ProxyControlStreamMsgType `protobuf:"varint,2,opt,name=MessageType,proto3,enum=proxy.control.proto.ProxyControlStreamMsgType" json:"MessageType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ProxyControlStreamMsgHdr) Reset()         { *m = ProxyControlStreamMsgHdr{} }
func (m *ProxyControlStreamMsgHdr) String() string { return proto.CompactTextString(m) }
func (*ProxyControlStreamMsgHdr) ProtoMessage()    {}
func (*ProxyControlStreamMsgHdr) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{1}
}
func (m *ProxyControlStreamMsgHdr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyControlStreamMsgHdr.Unmarshal(m, b)
}
func (m *ProxyControlStreamMsgHdr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyControlStreamMsgHdr.Marshal(b, m, deterministic)
}
func (dst *ProxyControlStreamMsgHdr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyControlStreamMsgHdr.Merge(dst, src)
}
func (m *ProxyControlStreamMsgHdr) XXX_Size() int {
	return xxx_messageInfo_ProxyControlStreamMsgHdr.Size(m)
}
func (m *ProxyControlStreamMsgHdr) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyControlStreamMsgHdr.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyControlStreamMsgHdr proto.InternalMessageInfo

func (m *ProxyControlStreamMsgHdr) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *ProxyControlStreamMsgHdr) GetMessageType() ProxyControlStreamMsgType {
	if m != nil {
		return m.MessageType
	}
	return ProxyControlStreamMsgType_REQUEST
}

type ProxyControlStreamMsgBody struct {
	// 方法版本
	Version int32 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	// 方法名
	Method string `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	// 参数
	Values [][]byte `protobuf:"bytes,3,rep,name=Values,proto3" json:"Values,omitempty"`
	// 状态码
	StatusCode int32 `protobuf:"varint,4,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// 自定义报错信息
	Reason               string   `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyControlStreamMsgBody) Reset()         { *m = ProxyControlStreamMsgBody{} }
func (m *ProxyControlStreamMsgBody) String() string { return proto.CompactTextString(m) }
func (*ProxyControlStreamMsgBody) ProtoMessage()    {}
func (*ProxyControlStreamMsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{2}
}
func (m *ProxyControlStreamMsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyControlStreamMsgBody.Unmarshal(m, b)
}
func (m *ProxyControlStreamMsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyControlStreamMsgBody.Marshal(b, m, deterministic)
}
func (dst *ProxyControlStreamMsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyControlStreamMsgBody.Merge(dst, src)
}
func (m *ProxyControlStreamMsgBody) XXX_Size() int {
	return xxx_messageInfo_ProxyControlStreamMsgBody.Size(m)
}
func (m *ProxyControlStreamMsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyControlStreamMsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyControlStreamMsgBody proto.InternalMessageInfo

func (m *ProxyControlStreamMsgBody) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProxyControlStreamMsgBody) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ProxyControlStreamMsgBody) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ProxyControlStreamMsgBody) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ProxyControlStreamMsgBody) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type AuthenticateRequest struct {
	SAID                 string   `protobuf:"bytes,1,opt,name=SAID,proto3" json:"SAID,omitempty"`
	SAKey                string   `protobuf:"bytes,2,opt,name=SAKey,proto3" json:"SAKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{3}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetSAID() string {
	if m != nil {
		return m.SAID
	}
	return ""
}

func (m *AuthenticateRequest) GetSAKey() string {
	if m != nil {
		return m.SAKey
	}
	return ""
}

type RegisterServiceRequest struct {
	Services             []*RegisterServiceValue `protobuf:"bytes,1,rep,name=Services,proto3" json:"Services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RegisterServiceRequest) Reset()         { *m = RegisterServiceRequest{} }
func (m *RegisterServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceRequest) ProtoMessage()    {}
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{4}
}
func (m *RegisterServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceRequest.Unmarshal(m, b)
}
func (m *RegisterServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceRequest.Merge(dst, src)
}
func (m *RegisterServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceRequest.Size(m)
}
func (m *RegisterServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceRequest proto.InternalMessageInfo

func (m *RegisterServiceRequest) GetServices() []*RegisterServiceValue {
	if m != nil {
		return m.Services
	}
	return nil
}

type RegisterServiceValue struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServicePort          int32    `protobuf:"varint,2,opt,name=ServicePort,proto3" json:"ServicePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServiceValue) Reset()         { *m = RegisterServiceValue{} }
func (m *RegisterServiceValue) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceValue) ProtoMessage()    {}
func (*RegisterServiceValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{5}
}
func (m *RegisterServiceValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceValue.Unmarshal(m, b)
}
func (m *RegisterServiceValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceValue.Marshal(b, m, deterministic)
}
func (dst *RegisterServiceValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceValue.Merge(dst, src)
}
func (m *RegisterServiceValue) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceValue.Size(m)
}
func (m *RegisterServiceValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceValue.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceValue proto.InternalMessageInfo

func (m *RegisterServiceValue) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RegisterServiceValue) GetServicePort() int32 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

type NewConnectionEvent struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	RemoteAddr           string   `protobuf:"bytes,3,opt,name=RemoteAddr,proto3" json:"RemoteAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewConnectionEvent) Reset()         { *m = NewConnectionEvent{} }
func (m *NewConnectionEvent) String() string { return proto.CompactTextString(m) }
func (*NewConnectionEvent) ProtoMessage()    {}
func (*NewConnectionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_control_cf5b292bcd47eb22, []int{6}
}
func (m *NewConnectionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewConnectionEvent.Unmarshal(m, b)
}
func (m *NewConnectionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewConnectionEvent.Marshal(b, m, deterministic)
}
func (dst *NewConnectionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewConnectionEvent.Merge(dst, src)
}
func (m *NewConnectionEvent) XXX_Size() int {
	return xxx_messageInfo_NewConnectionEvent.Size(m)
}
func (m *NewConnectionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NewConnectionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NewConnectionEvent proto.InternalMessageInfo

func (m *NewConnectionEvent) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *NewConnectionEvent) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *NewConnectionEvent) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyControlStreamMsg)(nil), "proxy.control.proto.ProxyControlStreamMsg")
	proto.RegisterType((*ProxyControlStreamMsgHdr)(nil), "proxy.control.proto.ProxyControlStreamMsgHdr")
	proto.RegisterType((*ProxyControlStreamMsgBody)(nil), "proxy.control.proto.ProxyControlStreamMsgBody")
	proto.RegisterType((*AuthenticateRequest)(nil), "proxy.control.proto.AuthenticateRequest")
	proto.RegisterType((*RegisterServiceRequest)(nil), "proxy.control.proto.RegisterServiceRequest")
	proto.RegisterType((*RegisterServiceValue)(nil), "proxy.control.proto.RegisterServiceValue")
	proto.RegisterType((*NewConnectionEvent)(nil), "proxy.control.proto.NewConnectionEvent")
	proto.RegisterEnum("proxy.control.proto.ProxyControlStreamMsgType", ProxyControlStreamMsgType_name, ProxyControlStreamMsgType_value)
}

func init() {
	proto.RegisterFile("pkg/datatunnel/v2/proto/proxy_control.proto", fileDescriptor_proxy_control_cf5b292bcd47eb22)
}

var fileDescriptor_proxy_control_cf5b292bcd47eb22 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x8e, 0xd2, 0x40,
	0x18, 0xc5, 0xed, 0x96, 0x3f, 0xcb, 0x57, 0x54, 0x32, 0xbb, 0x6e, 0xaa, 0x31, 0x86, 0xf4, 0x0a,
	0xd7, 0x58, 0x0c, 0x3e, 0xc0, 0x06, 0xb0, 0x66, 0x89, 0x81, 0xc5, 0x29, 0x6e, 0xe2, 0xde, 0x6c,
	0x2a, 0xfd, 0x02, 0xcd, 0xc2, 0x0c, 0xce, 0x0c, 0x28, 0x37, 0x3e, 0x80, 0xcf, 0xa0, 0xef, 0x6a,
	0x66, 0xda, 0x5d, 0xbb, 0x1b, 0x48, 0xe0, 0xa6, 0x9d, 0xf3, 0xcb, 0x9c, 0xd3, 0xd3, 0xe9, 0x97,
	0xc2, 0x9b, 0xc5, 0xcd, 0xa4, 0x19, 0x47, 0x2a, 0x52, 0x4b, 0xc6, 0x70, 0xd6, 0x5c, 0xb5, 0x9a,
	0x0b, 0xc1, 0x15, 0xd7, 0xd7, 0x9f, 0xeb, 0xeb, 0x31, 0x67, 0x4a, 0xf0, 0x99, 0x6f, 0x18, 0x39,
	0x32, 0xd0, 0xbf, 0x07, 0xbd, 0x3f, 0x16, 0x3c, 0x1b, 0x6a, 0xde, 0x4d, 0x71, 0xa8, 0x04, 0x46,
	0xf3, 0xbe, 0x9c, 0x90, 0x33, 0xb0, 0xcf, 0x63, 0xe1, 0x5a, 0x75, 0xab, 0xe1, 0xb4, 0xde, 0xfa,
	0x1b, 0xcc, 0xfe, 0x46, 0xe3, 0x79, 0x2c, 0xa8, 0x76, 0x92, 0x0e, 0x14, 0x3a, 0x3c, 0x5e, 0xbb,
	0x07, 0x26, 0xc1, 0xdf, 0x3d, 0x41, 0xbb, 0xa8, 0xf1, 0x7a, 0xbf, 0x2d, 0x70, 0xb7, 0x3d, 0x85,
	0xbc, 0x84, 0x4a, 0x1f, 0xa5, 0x8c, 0x26, 0xd8, 0x8b, 0x4d, 0x4f, 0x9b, 0xfe, 0x07, 0x64, 0x08,
	0x4e, 0x26, 0x46, 0xeb, 0x05, 0x9a, 0x16, 0x4f, 0xf6, 0x69, 0xa1, 0x5d, 0x34, 0x1f, 0xe1, 0xfd,
	0xb5, 0xe0, 0xf9, 0xd6, 0xc2, 0xc4, 0x85, 0xf2, 0x25, 0x0a, 0x99, 0x70, 0x66, 0xba, 0x14, 0xe9,
	0xad, 0x24, 0x27, 0x50, 0xea, 0xa3, 0x9a, 0xf2, 0xd8, 0x94, 0xa8, 0xd0, 0x4c, 0x69, 0x7e, 0x19,
	0xcd, 0x96, 0x28, 0x5d, 0xbb, 0x6e, 0x37, 0xaa, 0x34, 0x53, 0xe4, 0x15, 0x40, 0xa8, 0x3f, 0xa9,
	0xec, 0xf2, 0x18, 0xdd, 0x82, 0x09, 0xcb, 0x11, 0xed, 0xa3, 0x18, 0x49, 0xce, 0xdc, 0x62, 0x9a,
	0x97, 0x2a, 0xef, 0x0c, 0x8e, 0xda, 0x4b, 0x35, 0x45, 0xa6, 0x92, 0x71, 0xa4, 0x90, 0xe2, 0xf7,
	0x25, 0x4a, 0x45, 0x08, 0x14, 0xc2, 0x76, 0xef, 0x83, 0x69, 0x55, 0xa1, 0x66, 0x4d, 0x8e, 0xa1,
	0x18, 0xb6, 0x3f, 0xe1, 0x3a, 0x6b, 0x94, 0x0a, 0xef, 0x1a, 0x4e, 0x28, 0x4e, 0x12, 0xa9, 0x50,
	0x84, 0x28, 0x56, 0xc9, 0xf8, 0x2e, 0x23, 0x80, 0xc3, 0x8c, 0x48, 0xd7, 0xaa, 0xdb, 0x0d, 0xa7,
	0xf5, 0x7a, 0xe3, 0x49, 0x3e, 0xb0, 0x9b, 0x17, 0xa2, 0x77, 0x56, 0xef, 0x0a, 0x8e, 0x37, 0xed,
	0x20, 0x75, 0x70, 0x32, 0x3d, 0x88, 0xe6, 0x98, 0x35, 0xcd, 0xa3, 0xdc, 0x8e, 0x21, 0x17, 0xca,
	0xd4, 0x2e, 0xd2, 0x3c, 0xf2, 0xa6, 0x40, 0x06, 0xf8, 0xa3, 0xcb, 0x19, 0xc3, 0xb1, 0x4a, 0x38,
	0x0b, 0x56, 0xc8, 0xd4, 0x0e, 0xc9, 0x35, 0xb0, 0x6f, 0x0f, 0xa2, 0x4a, 0xf5, 0x52, 0x9f, 0x3f,
	0xc5, 0x39, 0x57, 0xd8, 0x8e, 0x63, 0xe1, 0xda, 0xc6, 0x92, 0x23, 0xa7, 0x9d, 0x2d, 0x63, 0xa0,
	0x87, 0x84, 0x38, 0x50, 0xa6, 0xc1, 0xe7, 0x2f, 0x41, 0x38, 0xaa, 0x3d, 0x22, 0x55, 0x38, 0xa4,
	0x41, 0x38, 0xbc, 0x18, 0x84, 0x41, 0xcd, 0x22, 0x00, 0xa5, 0xc1, 0xc5, 0xa8, 0xf7, 0xf1, 0x6b,
	0xed, 0xa0, 0xf5, 0x0b, 0x9e, 0xe6, 0x33, 0x66, 0x28, 0xc8, 0x0d, 0x3c, 0xbe, 0x97, 0x48, 0x4e,
	0x77, 0x1f, 0xd6, 0x17, 0x7b, 0xec, 0x6d, 0x58, 0xef, 0xac, 0x4e, 0xe5, 0xaa, 0xec, 0xa7, 0xff,
	0x8a, 0x6f, 0x25, 0x73, 0x7b, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xac, 0x0d, 0x82, 0x4d,
	0x04, 0x00, 0x00,
}
