// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modules/supervisor/proto/supervisor.proto

package proto // import "./proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/protobuf/types/known/emptypb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateItem struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	NewImage             string   `protobuf:"bytes,2,opt,name=NewImage,proto3" json:"NewImage,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItem) Reset()         { *m = UpdateItem{} }
func (m *UpdateItem) String() string { return proto.CompactTextString(m) }
func (*UpdateItem) ProtoMessage()    {}
func (*UpdateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{0}
}
func (m *UpdateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItem.Unmarshal(m, b)
}
func (m *UpdateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItem.Marshal(b, m, deterministic)
}
func (dst *UpdateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItem.Merge(dst, src)
}
func (m *UpdateItem) XXX_Size() int {
	return xxx_messageInfo_UpdateItem.Size(m)
}
func (m *UpdateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItem.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItem proto.InternalMessageInfo

func (m *UpdateItem) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *UpdateItem) GetNewImage() string {
	if m != nil {
		return m.NewImage
	}
	return ""
}

func (m *UpdateItem) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Extension struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extension) Reset()         { *m = Extension{} }
func (m *Extension) String() string { return proto.CompactTextString(m) }
func (*Extension) ProtoMessage()    {}
func (*Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{1}
}
func (m *Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extension.Unmarshal(m, b)
}
func (m *Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extension.Marshal(b, m, deterministic)
}
func (dst *Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extension.Merge(dst, src)
}
func (m *Extension) XXX_Size() int {
	return xxx_messageInfo_Extension.Size(m)
}
func (m *Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_Extension proto.InternalMessageInfo

func (m *Extension) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Plugin struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{2}
}
func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (dst *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(dst, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Plugin) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Plugin) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Plugin) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Smartassistant struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Registry             string   `protobuf:"bytes,3,opt,name=Registry,proto3" json:"Registry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Smartassistant) Reset()         { *m = Smartassistant{} }
func (m *Smartassistant) String() string { return proto.CompactTextString(m) }
func (*Smartassistant) ProtoMessage()    {}
func (*Smartassistant) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{3}
}
func (m *Smartassistant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Smartassistant.Unmarshal(m, b)
}
func (m *Smartassistant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Smartassistant.Marshal(b, m, deterministic)
}
func (dst *Smartassistant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Smartassistant.Merge(dst, src)
}
func (m *Smartassistant) XXX_Size() int {
	return xxx_messageInfo_Smartassistant.Size(m)
}
func (m *Smartassistant) XXX_DiscardUnknown() {
	xxx_messageInfo_Smartassistant.DiscardUnknown(m)
}

var xxx_messageInfo_Smartassistant proto.InternalMessageInfo

func (m *Smartassistant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Smartassistant) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Smartassistant) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

type RestartReq struct {
	Image                string   `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
	NewImage             string   `protobuf:"bytes,2,opt,name=NewImage,proto3" json:"NewImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartReq) Reset()         { *m = RestartReq{} }
func (m *RestartReq) String() string { return proto.CompactTextString(m) }
func (*RestartReq) ProtoMessage()    {}
func (*RestartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{4}
}
func (m *RestartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartReq.Unmarshal(m, b)
}
func (m *RestartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartReq.Marshal(b, m, deterministic)
}
func (dst *RestartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartReq.Merge(dst, src)
}
func (m *RestartReq) XXX_Size() int {
	return xxx_messageInfo_RestartReq.Size(m)
}
func (m *RestartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartReq.DiscardUnknown(m)
}

var xxx_messageInfo_RestartReq proto.InternalMessageInfo

func (m *RestartReq) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *RestartReq) GetNewImage() string {
	if m != nil {
		return m.NewImage
	}
	return ""
}

type BackupReq struct {
	Note                 string          `protobuf:"bytes,1,opt,name=Note,proto3" json:"Note,omitempty"`
	Smartassistant       *Smartassistant `protobuf:"bytes,2,opt,name=Smartassistant,proto3" json:"Smartassistant,omitempty"`
	Plugins              []*Plugin       `protobuf:"bytes,3,rep,name=Plugins,proto3" json:"Plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BackupReq) Reset()         { *m = BackupReq{} }
func (m *BackupReq) String() string { return proto.CompactTextString(m) }
func (*BackupReq) ProtoMessage()    {}
func (*BackupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{5}
}
func (m *BackupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupReq.Unmarshal(m, b)
}
func (m *BackupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupReq.Marshal(b, m, deterministic)
}
func (dst *BackupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupReq.Merge(dst, src)
}
func (m *BackupReq) XXX_Size() int {
	return xxx_messageInfo_BackupReq.Size(m)
}
func (m *BackupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupReq.DiscardUnknown(m)
}

var xxx_messageInfo_BackupReq proto.InternalMessageInfo

func (m *BackupReq) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *BackupReq) GetSmartassistant() *Smartassistant {
	if m != nil {
		return m.Smartassistant
	}
	return nil
}

func (m *BackupReq) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type RestoreReq struct {
	File                 string          `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	Smartassistant       *Smartassistant `protobuf:"bytes,2,opt,name=Smartassistant,proto3" json:"Smartassistant,omitempty"`
	Plugins              []*Plugin       `protobuf:"bytes,3,rep,name=Plugins,proto3" json:"Plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RestoreReq) Reset()         { *m = RestoreReq{} }
func (m *RestoreReq) String() string { return proto.CompactTextString(m) }
func (*RestoreReq) ProtoMessage()    {}
func (*RestoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{6}
}
func (m *RestoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreReq.Unmarshal(m, b)
}
func (m *RestoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreReq.Marshal(b, m, deterministic)
}
func (dst *RestoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreReq.Merge(dst, src)
}
func (m *RestoreReq) XXX_Size() int {
	return xxx_messageInfo_RestoreReq.Size(m)
}
func (m *RestoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreReq proto.InternalMessageInfo

func (m *RestoreReq) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *RestoreReq) GetSmartassistant() *Smartassistant {
	if m != nil {
		return m.Smartassistant
	}
	return nil
}

func (m *RestoreReq) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type UpdateReq struct {
	UpdateItems          []*UpdateItem `protobuf:"bytes,1,rep,name=UpdateItems,proto3" json:"UpdateItems,omitempty"`
	SoftwareVersion      string        `protobuf:"bytes,2,opt,name=SoftwareVersion,proto3" json:"SoftwareVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{7}
}
func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (dst *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(dst, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetUpdateItems() []*UpdateItem {
	if m != nil {
		return m.UpdateItems
	}
	return nil
}

func (m *UpdateReq) GetSoftwareVersion() string {
	if m != nil {
		return m.SoftwareVersion
	}
	return ""
}

type UpdateSystemReq struct {
	Image                string   `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSystemReq) Reset()         { *m = UpdateSystemReq{} }
func (m *UpdateSystemReq) String() string { return proto.CompactTextString(m) }
func (*UpdateSystemReq) ProtoMessage()    {}
func (*UpdateSystemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{8}
}
func (m *UpdateSystemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSystemReq.Unmarshal(m, b)
}
func (m *UpdateSystemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSystemReq.Marshal(b, m, deterministic)
}
func (dst *UpdateSystemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSystemReq.Merge(dst, src)
}
func (m *UpdateSystemReq) XXX_Size() int {
	return xxx_messageInfo_UpdateSystemReq.Size(m)
}
func (m *UpdateSystemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSystemReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSystemReq proto.InternalMessageInfo

func (m *UpdateSystemReq) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{9}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type GetSystemInfoResp struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemInfoResp) Reset()         { *m = GetSystemInfoResp{} }
func (m *GetSystemInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetSystemInfoResp) ProtoMessage()    {}
func (*GetSystemInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{10}
}
func (m *GetSystemInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemInfoResp.Unmarshal(m, b)
}
func (m *GetSystemInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemInfoResp.Marshal(b, m, deterministic)
}
func (dst *GetSystemInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemInfoResp.Merge(dst, src)
}
func (m *GetSystemInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetSystemInfoResp.Size(m)
}
func (m *GetSystemInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemInfoResp proto.InternalMessageInfo

func (m *GetSystemInfoResp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetExtensionsResp struct {
	Extensions           []*Extension `protobuf:"bytes,1,rep,name=Extensions,proto3" json:"Extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetExtensionsResp) Reset()         { *m = GetExtensionsResp{} }
func (m *GetExtensionsResp) String() string { return proto.CompactTextString(m) }
func (*GetExtensionsResp) ProtoMessage()    {}
func (*GetExtensionsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_supervisor_ced72216be93e94a, []int{11}
}
func (m *GetExtensionsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExtensionsResp.Unmarshal(m, b)
}
func (m *GetExtensionsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExtensionsResp.Marshal(b, m, deterministic)
}
func (dst *GetExtensionsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExtensionsResp.Merge(dst, src)
}
func (m *GetExtensionsResp) XXX_Size() int {
	return xxx_messageInfo_GetExtensionsResp.Size(m)
}
func (m *GetExtensionsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExtensionsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetExtensionsResp proto.InternalMessageInfo

func (m *GetExtensionsResp) GetExtensions() []*Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateItem)(nil), "supervisor.proto.UpdateItem")
	proto.RegisterType((*Extension)(nil), "supervisor.proto.Extension")
	proto.RegisterType((*Plugin)(nil), "supervisor.proto.Plugin")
	proto.RegisterType((*Smartassistant)(nil), "supervisor.proto.Smartassistant")
	proto.RegisterType((*RestartReq)(nil), "supervisor.proto.RestartReq")
	proto.RegisterType((*BackupReq)(nil), "supervisor.proto.BackupReq")
	proto.RegisterType((*RestoreReq)(nil), "supervisor.proto.RestoreReq")
	proto.RegisterType((*UpdateReq)(nil), "supervisor.proto.UpdateReq")
	proto.RegisterType((*UpdateSystemReq)(nil), "supervisor.proto.UpdateSystemReq")
	proto.RegisterType((*Response)(nil), "supervisor.proto.Response")
	proto.RegisterType((*GetSystemInfoResp)(nil), "supervisor.proto.GetSystemInfoResp")
	proto.RegisterType((*GetExtensionsResp)(nil), "supervisor.proto.GetExtensionsResp")
}

func init() {
	proto.RegisterFile("modules/supervisor/proto/supervisor.proto", fileDescriptor_supervisor_ced72216be93e94a)
}

var fileDescriptor_supervisor_ced72216be93e94a = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xba, 0xfd, 0xa0, 0x53, 0xd8, 0x05, 0x0b, 0xad, 0xa2, 0x2e, 0x12, 0x25, 0x1c, 0x28,
	0x07, 0x52, 0xa9, 0xdc, 0x40, 0x5a, 0x89, 0xb2, 0x0b, 0x54, 0x82, 0xd5, 0x2a, 0x15, 0x1c, 0xf6,
	0x80, 0x64, 0xb6, 0xd3, 0x2a, 0xa2, 0x89, 0x83, 0xed, 0xb0, 0xf4, 0x17, 0xf0, 0x2b, 0xe0, 0xb7,
	0x22, 0xc7, 0xae, 0x93, 0x34, 0x69, 0x11, 0x27, 0x4e, 0xcd, 0x8c, 0xdf, 0x3c, 0x3f, 0xcf, 0x3c,
	0xbb, 0xf0, 0x34, 0x62, 0xf3, 0x74, 0x85, 0x62, 0x24, 0xd2, 0x04, 0xf9, 0xf7, 0x50, 0x30, 0x3e,
	0x4a, 0x38, 0x93, 0xac, 0x90, 0xf0, 0xb3, 0x04, 0xb9, 0xbb, 0x9d, 0xe9, 0x9f, 0x2c, 0x19, 0x5b,
	0xae, 0x50, 0x17, 0x7c, 0x49, 0x17, 0x23, 0x8c, 0x12, 0xb9, 0xd6, 0x8b, 0xde, 0x1c, 0xe0, 0x63,
	0x32, 0xa7, 0x12, 0xa7, 0x12, 0x23, 0x32, 0x80, 0xde, 0x4c, 0x15, 0x5f, 0xe3, 0x05, 0x8d, 0xd0,
	0x75, 0x06, 0xce, 0xb0, 0x1b, 0x14, 0x53, 0xa4, 0x0f, 0xb7, 0x2e, 0xf0, 0x66, 0x1a, 0xd1, 0x25,
	0xba, 0x8d, 0x6c, 0xd9, 0xc6, 0xc4, 0x85, 0xce, 0x27, 0xe4, 0x22, 0x64, 0xb1, 0x7b, 0x90, 0x2d,
	0x6d, 0x42, 0xef, 0x21, 0x74, 0xcf, 0x7f, 0x48, 0x8c, 0x55, 0x40, 0x08, 0x34, 0x0b, 0xec, 0xd9,
	0xb7, 0xf7, 0x19, 0xda, 0x97, 0xab, 0x74, 0x19, 0xc6, 0xe4, 0x10, 0x1a, 0xd3, 0x33, 0xb3, 0xd6,
	0x98, 0x9e, 0x91, 0xfb, 0xd0, 0x9a, 0x70, 0x1a, 0xcf, 0xcd, 0x6e, 0x3a, 0x50, 0x59, 0xad, 0x41,
	0x6f, 0xd4, 0xaa, 0x08, 0x68, 0x96, 0x05, 0x5c, 0xc1, 0xe1, 0x2c, 0xa2, 0x5c, 0x52, 0x21, 0x42,
	0x21, 0x69, 0x2c, 0xeb, 0x54, 0x14, 0xeb, 0x1b, 0xa5, 0x7a, 0x75, 0xec, 0x00, 0x97, 0xa1, 0x90,
	0x7c, 0x6d, 0xb6, 0xb4, 0xb1, 0x77, 0x0a, 0x10, 0xa0, 0x90, 0x94, 0xcb, 0x00, 0xbf, 0xe5, 0xca,
	0x9c, 0xa2, 0xb2, 0x3d, 0x6d, 0xf3, 0x7e, 0x39, 0xd0, 0x9d, 0xd0, 0xeb, 0xaf, 0x69, 0xa2, 0xea,
	0x95, 0x2e, 0x26, 0x73, 0x5d, 0x4c, 0x22, 0x79, 0xb7, 0xad, 0x3e, 0xe3, 0xe8, 0x8d, 0x07, 0xfe,
	0xf6, 0xb0, 0xfd, 0x32, 0x2e, 0xd8, 0x3e, 0xf5, 0x18, 0x3a, 0xba, 0xcf, 0xc2, 0x3d, 0x18, 0x1c,
	0x0c, 0x7b, 0x63, 0xb7, 0x4a, 0xa1, 0x01, 0xc1, 0x06, 0xe8, 0xfd, 0x76, 0xf4, 0x01, 0x19, 0x47,
	0x23, 0xf0, 0x4d, 0xb8, 0xb2, 0x02, 0xd5, 0xf7, 0x7f, 0x16, 0x98, 0x42, 0x57, 0x7b, 0x58, 0xc9,
	0x3b, 0x85, 0x5e, 0x6e, 0x68, 0xe1, 0x3a, 0x19, 0xc9, 0x83, 0x2a, 0x49, 0x0e, 0x0a, 0x8a, 0x05,
	0x64, 0x08, 0x47, 0x33, 0xb6, 0x90, 0x37, 0x94, 0x63, 0xd9, 0x0b, 0xdb, 0x69, 0xef, 0x09, 0x1c,
	0xe9, 0xc2, 0xd9, 0x5a, 0x28, 0x9a, 0x5d, 0xc3, 0xf7, 0x5e, 0x28, 0xf3, 0x88, 0x84, 0xc5, 0x02,
	0xc9, 0x31, 0xb4, 0x85, 0xa4, 0x32, 0x15, 0x19, 0xa4, 0x15, 0x98, 0x48, 0xe5, 0x39, 0x52, 0x61,
	0x77, 0x33, 0x91, 0xf7, 0x0c, 0xee, 0xbd, 0x45, 0xa9, 0x77, 0x98, 0xc6, 0x0b, 0xa6, 0x88, 0x8a,
	0x3e, 0x75, 0xca, 0x3e, 0xbf, 0xcc, 0xe0, 0xf6, 0xae, 0x89, 0x0c, 0xfe, 0x12, 0x20, 0xcf, 0x98,
	0x8e, 0x9c, 0x54, 0x3b, 0x62, 0x31, 0x41, 0x01, 0x3e, 0xfe, 0xd9, 0x04, 0x98, 0x59, 0x28, 0x79,
	0x0d, 0x1d, 0x63, 0x76, 0x52, 0xd3, 0xd4, 0xfc, 0x1e, 0xf4, 0xfb, 0xb5, 0xab, 0xba, 0x09, 0xaf,
	0xa0, 0xad, 0x0d, 0x4f, 0x6a, 0x64, 0xd8, 0xab, 0xb0, 0x97, 0xc2, 0xe8, 0x60, 0x1c, 0x77, 0xe9,
	0xd0, 0x76, 0xfd, 0x9b, 0x0e, 0x3d, 0xc1, 0x3a, 0x1d, 0xd6, 0x52, 0x7b, 0x29, 0x3e, 0xc0, 0xed,
	0xa2, 0x09, 0xc8, 0xa3, 0x5d, 0x44, 0xd6, 0x24, 0x7b, 0xe9, 0xde, 0xc3, 0x9d, 0xd2, 0xb8, 0xc9,
	0xb1, 0xaf, 0x5f, 0x6f, 0x7f, 0xf3, 0x7a, 0xfb, 0xe7, 0xea, 0xf5, 0xee, 0x3f, 0xae, 0x92, 0x54,
	0x7d, 0xa2, 0xd9, 0xf2, 0x61, 0xfe, 0x23, 0x5b, 0xd9, 0x46, 0x93, 0xee, 0x55, 0xc7, 0x37, 0x7f,
	0x22, 0xed, 0xec, 0xe7, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xe1, 0x2f, 0x56, 0x98,
	0x06, 0x00, 0x00,
}
